apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
  namespace: elkia
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: etcd
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: peer
      port: 2380
      targetPort: peer
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: elkia
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: etcd
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: peer
      port: 2380
      targetPort: peer
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: etcd
