apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../elkia-authserver/overlays/default
  - ../../../elkia-apiserver/overlays/default
  - ../../../elkia-gateway/overlays/default
  - ../../../kratos/overlays/default
  - ../../../etcd/overlays/default
  - ../../../mysql/overlays/default
