apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../elkia-authserver/overlays/default
  - ../../../elkia-fleet/overlays/default
  - ../../../elkia-gateway/overlays/default
  - ingress.yaml