apiVersion: apps
kind: Deployment
metadata:
  name: elkia-authserver
  namespace: elkia
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elkia-authserver
    spec:
      containers:
        - name: elkia-authserver
          image: gcr.io/infinity-blackhole/elkia-authserver
          args:
            - --elkia-apiserver-endpoint=http://elkia-apiserver:8080
          ports:
            - containerPort: 4123
              name: elkia
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 128Mi
